spring :
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
   name: config-server
server:
  port: 8848
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka

